### ISSUE TITLE
Meny eller tillbakaknapp

### ISSUE THREAD

**Issue by Moaclayco** [edgesoft/moaclayco#56]
Något som gör det "enklare" för kunder att förstå hur de ska kunna se alla kollektioner och hitta lättare.

**Comment by edgesoft** [comment]
@Moaclayco Vi du visa i bilder hur det är tänkt att se ut? OBS! Ska fungera på mobil/platta och telefon. Se till att både "bag" knappen (kassa knappen) samt meny fungerar på alla enheter som design innan denna byggs.
